//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.03 at 07:48:12 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "D:\\JD2018-11-13\\src\\by\\it\\zakharenko\\jd02_07\\clients.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.zakharenko.jd02_09.beans;
