//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.28 at 05:43:28 PM MSK 
//


package by.it.kovalyova.jd03_03.beans;

public class Flat {

    protected long id;
    protected String description;
    protected String address;
    protected long rooms;
    protected long floor;
    protected long floors;
    protected float area;

    public Flat(){
    }

    public Flat(long id, String description, String address, long rooms, long floor,
                 long floors, float area) {
        this.id = id;
        this.rooms = rooms;
        this.floor = floors;
        this.description = description;
        this.address = address;
        this.area = area;

    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link long }
     *     
     */
    public long getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link long }
     *     
     */
    public void setRooms(long value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link long }
     *     
     */
    public long getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link long }
     *     
     */
    public void setFloor(long value) {
        this.floor = value;
    }

    /**
     * Gets the value of the floors property.
     * 
     * @return
     *     possible object is
     *     {@link long }
     *     
     */
    public long getFloors() {
        return floors;
    }

    /**
     * Sets the value of the floors property.
     * 
     * @param value
     *     allowed object is
     *     {@link long }
     *     
     */
    public void setFloors(long value) {
        this.floors = value;
    }

    /**
     * Gets the value of the area property.
     * 
     */
    public float getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     */
    public void setArea(float value) {
        this.area = value;
    }

}
