-- MySQL Script generated by MySQL Workbench
-- 02/03/19 13:58:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zakharnk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zakharnk` ;

-- -----------------------------------------------------
-- Schema zakharnk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zakharnk` DEFAULT CHARACTER SET utf8 ;
USE `zakharnk` ;

-- -----------------------------------------------------
-- Table `zakharnk`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zakharnk`.`roles` ;

CREATE TABLE IF NOT EXISTS `zakharnk`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zakharnk`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zakharnk`.`clients` ;

CREATE TABLE IF NOT EXISTS `zakharnk`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `e-mail` VARCHAR(50) NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `phone_number` VARCHAR(50) NULL DEFAULT NULL,
  `roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_clients_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `zakharnk`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zakharnk`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zakharnk`.`orders` ;

CREATE TABLE IF NOT EXISTS `zakharnk`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `item` VARCHAR(100) NULL DEFAULT NULL,
  `item_id` INT(11) NOT NULL,
  `colour` VARCHAR(50) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `clients_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_clients_idx` (`clients_id` ASC),
  CONSTRAINT `fk_orders_clients`
    FOREIGN KEY (`clients_id`)
    REFERENCES `zakharnk`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zakharnk`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `zakharnk`;
INSERT INTO `zakharnk`.`roles` (`id`, `role`) VALUES (DEFAULT, 'admin');
INSERT INTO `zakharnk`.`roles` (`id`, `role`) VALUES (DEFAULT, 'client');
INSERT INTO `zakharnk`.`roles` (`id`, `role`) VALUES (DEFAULT, 'guest');

COMMIT;


-- -----------------------------------------------------
-- Data for table `zakharnk`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `zakharnk`;
INSERT INTO `zakharnk`.`clients` (`id`, `e-mail`, `login`, `password`, `phone_number`, `roles_id`) VALUES (DEFAULT, 'admin@gmail.com', 'admin', 'admin', '+375297658895', 1);
INSERT INTO `zakharnk`.`clients` (`id`, `e-mail`, `login`, `password`, `phone_number`, `roles_id`) VALUES (DEFAULT, 'lizazakharenko@gmail.com', 'liza', 'liza', '+375297658895', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `zakharnk`.`orders`
-- -----------------------------------------------------
START TRANSACTION;
USE `zakharnk`;
INSERT INTO `zakharnk`.`orders` (`id`, `name`, `item`, `item_id`, `colour`, `price`, `address`, `clients_id`) VALUES (DEFAULT, 'Vacuum cleaner', 'Samsung SC5241', 1234, 'grey', 129, 'Minsk, Rokossovskogo ave, 145-173', 2);
INSERT INTO `zakharnk`.`orders` (`id`, `name`, `item`, `item_id`, `colour`, `price`, `address`, `clients_id`) VALUES (DEFAULT, 'Washing machine', 'LG F2J5HS3W', 1253, 'white', 799, 'Minsk, Rokossovskogo ave, 145-173', 2);

COMMIT;

