-- MySQL Script generated by MySQL Workbench
-- 01/18/19 23:31:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kovalyova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kovalyova` ;

-- -----------------------------------------------------
-- Schema kovalyova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kovalyova` DEFAULT CHARACTER SET utf8 ;
USE `kovalyova` ;

-- -----------------------------------------------------
-- Table `kovalyova`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kovalyova`.`roles` ;

CREATE TABLE IF NOT EXISTS `kovalyova`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovalyova`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kovalyova`.`users` ;

CREATE TABLE IF NOT EXISTS `kovalyova`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roles_id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `kovalyova`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovalyova`.`flats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kovalyova`.`flats` ;

CREATE TABLE IF NOT EXISTS `kovalyova`.`flats` (
  `id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(1000) NULL,
  `address` VARCHAR(100) NULL,
  `floor` INT NULL,
  `floors` INT NULL,
  `rooms` INT NULL,
  `area` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovalyova`.`ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kovalyova`.`ads` ;

CREATE TABLE IF NOT EXISTS `kovalyova`.`ads` (
  `id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `flats_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ads_users1_idx` (`users_id` ASC),
  INDEX `fk_ads_flats1_idx` (`flats_id` ASC),
  CONSTRAINT `fk_ads_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `kovalyova`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ads_flats1`
    FOREIGN KEY (`flats_id`)
    REFERENCES `kovalyova`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
