//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 12:42:00 AM MSK 
//


package by.it.vchernetski.jd02_09.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for garage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="garage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carplaces" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cars" type="{http://beans.jd02_09.vchernetski.it.by}cars" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "garage", propOrder = {
    "adress",
    "carplaces",
    "cars"
})
public class Garage {

    @XmlElement(required = true)
    protected String adress;
    protected int carplaces;
    @XmlElement(required = true)
    protected List<Cars> cars;

    @Override
    public String toString() {
        return "\n\t\t\tGarage{" +
                "adress='" + adress + '\'' +
                ",list carplaces=" + carplaces +
                ", cars=" + cars +
                '}';
    }

    /**
     * Gets the value of the adress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdress() {
        return adress;
    }

    /**
     * Sets the value of the adress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdress(String value) {
        this.adress = value;
    }

    /**
     * Gets the value of the carplaces property.
     * 
     */
    public int getCarplaces() {
        return carplaces;
    }

    /**
     * Sets the value of the carplaces property.
     * 
     */
    public void setCarplaces(int value) {
        this.carplaces = value;
    }

    /**
     * Gets the value of the cars property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cars property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCars().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cars }
     * 
     * 
     */
    public List<Cars> getCars() {
        if (cars == null) {
            cars = new ArrayList<Cars>();
        }
        return this.cars;
    }

}
