//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 09:20:41 PM MSK 
//


package by.it.zhivov.jd02_09.beans;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for Ad complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * <complexType name="Ad">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all>
 *         <element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="year" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         <element name="equipment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="mileage" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         <element name="crashed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="price" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       </all>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ad", propOrder = {
        "description",
        "brand",
        "model",
        "color",
        "body",
        "year",
        "equipment",
        "mileage",
        "crashed",
        "price"
})
public class Ad {

    @XmlElement(required = true)
    private String description;
    @XmlElement(required = true)
    private String brand;
    @XmlElement(required = true)
    private String model;
    @XmlElement(required = true)
    private String color;
    @XmlElement(required = true)
    private String body;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    private int year;
    @XmlElement(required = true)
    private String equipment;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    private int mileage;
    private boolean crashed;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected int price;

    public Ad() {    }

    public Ad(String description, String brand, String model, String color, String body, int year, String equipment, int mileage, boolean crashed, int price) {
        this.description = description;
        this.brand = brand;
        this.model = model;
        this.color = color;
        this.body = body;
        this.year = year;
        this.equipment = equipment;
        this.mileage = mileage;
        this.crashed = crashed;
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String value) {
        this.brand = value;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String value) {
        this.model = value;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String value) {
        this.color = value;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String value) {
        this.body = value;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int value) {
        this.year = value;
    }

    public String getEquipment() {
        return equipment;
    }

    public void setEquipment(String value) {
        this.equipment = value;
    }

    public int getMileage() {
        return mileage;
    }

    public void setMileage(int value) {
        this.mileage = value;
    }

    public boolean isCrashed() {
        return crashed;
    }

    public void setCrashed(boolean value) {
        this.crashed = value;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int value) {
        this.price = value;
    }

    @Override
    public String toString() {
        return "Ad {\n" +
                "\t\t\t\t\tdescription='" + description + '\'' + "\n" +
                "\t\t\t\t\ttbrand='" + brand + '\'' + "\n" +
                "\t\t\t\t\tmodel='" + model + '\'' + "\n" +
                "\t\t\t\t\tcolor='" + color + '\'' + "\n" +
                "\t\t\t\t\tbody='" + body + '\'' + "\n" +
                "\t\t\t\t\tyear=" + year + "\n" +
                "\t\t\t\t\tequipment='" + equipment + '\'' + "\n" +
                "\t\t\t\t\tmileage=" + mileage + "\n" +
                "\t\t\t\t\tcrashed=" + crashed + "\n" +
                "\t\t\t\t\tprice=" + price + "\n" +
                "\t\t\t\t\t}" + "\n\t\t\t\t";
    }
}
