//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 12:09:52 AM MSK 
//


package by.it.zhivov.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Admin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Admin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="login" type="{http://beans.jd02_09.zhivov.it.by/}Login"/>
 *         &lt;element name="password" type="{http://beans.jd02_09.zhivov.it.by/}Password"/>
 *         &lt;element name="privelegy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Admin", propOrder = {
    "login",
    "password",
    "privelegy"
})
public class Admin {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String login;
    @XmlElement(required = true)
    protected String password;
    protected boolean privelegy;

    public Admin() {
    }

    public Admin(String login, String password, boolean privelegy) {
        this.login = login;
        this.password = password;
        this.privelegy = privelegy;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the privelegy property.
     * 
     */
    public boolean isPrivelegy() {
        return privelegy;
    }

    /**
     * Sets the value of the privelegy property.
     * 
     */
    public void setPrivelegy(boolean value) {
        this.privelegy = value;
    }

    @Override
    public String toString() {
        return "\n\tAdmin {\n" +
                "\t\tlogin='" + login + '\'' +"\n"+
                "\t\tpassword='" + password + '\'' +"\n"+
                "\t\tprivelegy=" + privelegy +"\n"+
                "\t\t}";
    }

}
