//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 09:20:41 PM MSK 
//


package by.it.zhivov.jd02_09.beans;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for User complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * <complexType name="User">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://beans.jd02_09.zhivov.it.by/}Name"/>
 *         <element name="login" type="{http://beans.jd02_09.zhivov.it.by/}Login"/>
 *         <element name="password" type="{http://beans.jd02_09.zhivov.it.by/}Password"/>
 *         <element name="dateOfBirth" type="{http://beans.jd02_09.zhivov.it.by/}DateOfBirth"/>
 *         <element name="email" type="{http://beans.jd02_09.zhivov.it.by/}Email"/>
 *         <element name="tel" type="{http://beans.jd02_09.zhivov.it.by/}Tel"/>
 *         <element name="privelegy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="ads" type="{http://beans.jd02_09.zhivov.it.by/}Ads"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", propOrder = {
        "name",
        "login",
        "password",
        "dateOfBirth",
        "email",
        "tel",
        "privelegy",
        "ads"
})
public class User {

    @XmlElement(required = true)
    private String name;
    @XmlElement(required = true)
    @XmlID
    @XmlSchemaType(name = "ID")
    private String login;
    @XmlElement(required = true)
    private String password;
    @XmlElement(required = true)
    private String dateOfBirth;
    @XmlElement(required = true)
    private String email;
    @XmlElement(required = true)
    private String tel;
    private boolean privelegy;
    @XmlElement(required = true)
    private Ads ads = new Ads();

    public User() {
    }

    public User(String name, String login, String password, String dateOfBirth, String email, String tel, boolean privelegy, Ads ads) {
        this.name = name;
        this.login = login;
        this.password = password;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.tel = tel;
        this.privelegy = privelegy;
        this.ads = ads;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String value) {
        this.login = value;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String value) {
        this.password = value;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String value) {
        this.tel = value;
    }

    public boolean isPrivelegy() {
        return privelegy;
    }

    public void setPrivelegy(boolean value) {
        this.privelegy = value;
    }

    public Ads getAds() {
        return ads;
    }

    public void setAds(Ads value) {
        this.ads = value;
    }

    @Override
    public String toString() {
        return "User {\n" +
                "\t\tname='" + name + '\'' + "\n" +
                "\t\tlogin='" + login + '\'' + "\n" +
                "\t\tpassword='" + password + '\'' + "\n" +
                "\t\tdateOfBirth='" + dateOfBirth + '\'' + "\n" +
                "\t\temail='" + email + '\'' + "\n" +
                "\t\ttel='" + tel + '\'' + "\n" +
                "\t\tprivelegy=" + privelegy + "\n" +
                "\t\t" + ads + "\n" +
                "\t}";
    }
}
