//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 12:09:52 AM MSK 
//


package by.it.zhivov.jd02_09.beans;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for User complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="User">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://beans.jd02_09.zhivov.it.by/}Name"/>
 *         &lt;element name="login" type="{http://beans.jd02_09.zhivov.it.by/}Login"/>
 *         &lt;element name="password" type="{http://beans.jd02_09.zhivov.it.by/}Password"/>
 *         &lt;element name="dateOfBirth" type="{http://beans.jd02_09.zhivov.it.by/}DateOfBirth"/>
 *         &lt;element name="email" type="{http://beans.jd02_09.zhivov.it.by/}Email"/>
 *         &lt;element name="tel" type="{http://beans.jd02_09.zhivov.it.by/}Tel"/>
 *         &lt;element name="privelegy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ads" type="{http://beans.jd02_09.zhivov.it.by/}Ads"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", propOrder = {
        "name",
        "login",
        "password",
        "dateOfBirth",
        "email",
        "tel",
        "privelegy",
        "ads"
})
public class User {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String login;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String dateOfBirth;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String tel;
    protected boolean privelegy;
    @XmlElement(required = true)
    protected Ads ads;

    public User() {
    }

    public User(String name, String login, String password, String dateOfBirth, String email, String tel, Ads ads) {
        this.name = name;
        this.login = login;
        this.password = password;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.tel = tel;
        this.ads = ads;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the login property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the password property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the tel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTel() {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTel(String value) {
        this.tel = value;
    }

    /**
     * Gets the value of the privelegy property.
     */

    public Ads getAds() {
        return ads;
    }

    /**
     * Sets the value of the ads property.
     *
     * @param value allowed object is
     *              {@link Ads }
     */
    public void setAds(Ads value) {
        this.ads = value;
    }

    @Override
    public String toString() {
        return "User {\n" +
                "\t\tname='" + name + '\'' + "\n" +
                "\t\tlogin='" + login + '\'' + "\n" +
                "\t\tpassword='" + password + '\'' + "\n" +
                "\t\tdateOfBirth='" + dateOfBirth + '\'' + "\n" +
                "\t\temail='" + email + '\'' + "\n" +
                "\t\ttel='" + tel + '\'' + "\n" +
                "\t\t" + ads + "\n" +
                "\t}";
    }

}
