//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 10:48:31 PM MSK 
//


package by.it.nickgrudnitsky.jd02_09.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.nickgrudnitsky.jd02_09.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.nickgrudnitsky.jd02_09.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Twitch }
     * 
     */
    public Twitch createTwitch() {
        return new Twitch();
    }

    /**
     * Create an instance of {@link Viewers }
     * 
     */
    public Viewers createViewers() {
        return new Viewers();
    }

    /**
     * Create an instance of {@link Streamers }
     * 
     */
    public Streamers createStreamers() {
        return new Streamers();
    }

    /**
     * Create an instance of {@link Streamer }
     * 
     */
    public Streamer createStreamer() {
        return new Streamer();
    }

    /**
     * Create an instance of {@link Following }
     * 
     */
    public Following createFollowing() {
        return new Following();
    }

    /**
     * Create an instance of {@link Viewer }
     * 
     */
    public Viewer createViewer() {
        return new Viewer();
    }

    /**
     * Create an instance of {@link Followers }
     * 
     */
    public Followers createFollowers() {
        return new Followers();
    }

}
