//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 10:48:31 PM MSK 
//


package by.it.nickgrudnitsky.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Streamers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Streamers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="streamer" type="{http://beans.jd02_09.nickgrudnitsky.it.by/}Streamer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Streamers", propOrder = {
    "streamer"
})
public class Streamers {

    @Override
    public String toString() {
        return "\n\tStreamers{" +
                "streamer=" + streamer +
                '}';
    }

    protected Streamer streamer;

    /**
     * Gets the value of the streamer property.
     * 
     * @return
     *     possible object is
     *     {@link Streamer }
     *     
     */
    public Streamer getStreamer() {
        return streamer;
    }

    /**
     * Sets the value of the streamer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Streamer }
     *     
     */
    public void setStreamer(Streamer value) {
        this.streamer = value;
    }

}
