//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 10:48:31 PM MSK 
//


package by.it.nickgrudnitsky.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="viewers" type="{http://beans.jd02_09.nickgrudnitsky.it.by/}Viewers" minOccurs="0"/>
 *         &lt;element name="streamers" type="{http://beans.jd02_09.nickgrudnitsky.it.by/}Streamers" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "viewers",
    "streamers"
})
@XmlRootElement(name = "twitch")
public class Twitch {

    @Override
    public String toString() {
        return "\nTwitch{" +
                "viewers=" + viewers +
                ", streamers=" + streamers +
                '}';
    }

    protected Viewers viewers;
    protected Streamers streamers;

    /**
     * Gets the value of the viewers property.
     * 
     * @return
     *     possible object is
     *     {@link Viewers }
     *     
     */
    public Viewers getViewers() {
        return viewers;
    }

    /**
     * Sets the value of the viewers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Viewers }
     *     
     */
    public void setViewers(Viewers value) {
        this.viewers = value;
    }

    /**
     * Gets the value of the streamers property.
     * 
     * @return
     *     possible object is
     *     {@link Streamers }
     *     
     */
    public Streamers getStreamers() {
        return streamers;
    }

    /**
     * Sets the value of the streamers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Streamers }
     *     
     */
    public void setStreamers(Streamers value) {
        this.streamers = value;
    }

}
