//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 10:48:31 PM MSK 
//


package by.it.nickgrudnitsky.jd02_09.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Viewers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Viewers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="viewer" type="{http://beans.jd02_09.nickgrudnitsky.it.by/}Viewer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Viewers", propOrder = {
    "viewer"
})
public class Viewers {

    @Override
    public String toString() {
        return "\n\tViewers{" +
                "viewer=" + viewer +
                '}';
    }

    protected List<Viewer> viewer;

    /**
     * Gets the value of the viewer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Viewer }
     * 
     * 
     */
    public List<Viewer> getViewer() {
        if (viewer == null) {
            viewer = new ArrayList<Viewer>();
        }
        return this.viewer;
    }

}
