//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.16 at 10:49:36 PM MSK 
//


package by.it.kruglenja.jd02_09.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Part complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Part">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://beans.jd02_09.kruglenja.it.by}Description"/>
 *         &lt;element name="shops" type="{http://beans.jd02_09.kruglenja.it.by}Shops" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Part", propOrder = {
        "description",
        "shops"
})
public class Part {

    @XmlElement(required = true)
    protected Description description;
    @XmlElement(required = true)
    protected List<Shops> shops;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link Description }
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link Description }
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the shops property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shops property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShops().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Shops }
     */
    public List<Shops> getShops() {
        if (shops == null) {
            shops = new ArrayList<Shops>();
        }
        return this.shops;
    }

    @Override
    public String toString() {
        return "\n\tPart{" +
                "description=" + description +
                "\n\t\tshops=" + shops +
                "\n\t" + '}';
    }
}
