//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:10:58 AM MSK 
//


package by.it.naumenko.jd02_09.beens;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roles" type="{http://beens.jd02_09.naumenko.it.by}roles" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="users" type="{http://beens.jd02_09.naumenko.it.by}users" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cake" type="{http://beens.jd02_09.naumenko.it.by}cake" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="zakaz" type="{http://beens.jd02_09.naumenko.it.by}zakaz" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roles",
    "users",
    "cake",
    "zakaz"
})
@XmlRootElement(name = "cakes")
public class Cakes {

    protected List<Roles> roles;
    protected List<Users> users;
    protected List<Cake> cake;
    protected List<Zakaz> zakaz;

    /**
     * Gets the value of the roles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Roles }
     * 
     * 
     */
    public List<Roles> getRoles() {
        if (roles == null) {
            roles = new ArrayList<Roles>();
        }
        return this.roles;
    }

    /**
     * Gets the value of the users property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the users property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Users }
     * 
     * 
     */
    public List<Users> getUsers() {
        if (users == null) {
            users = new ArrayList<Users>();
        }
        return this.users;
    }

    /**
     * Gets the value of the cake property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cake property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCake().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cake }
     * 
     * 
     */
    public List<Cake> getCake() {
        if (cake == null) {
            cake = new ArrayList<Cake>();
        }
        return this.cake;
    }

    /**
     * Gets the value of the zakaz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zakaz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZakaz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Zakaz }
     * 
     * 
     */
    public List<Zakaz> getZakaz() {
        if (zakaz == null) {
            zakaz = new ArrayList<Zakaz>();
        }
        return this.zakaz;
    }

    @Override
    public String toString() {
        return "Cakes{" +
                "\n\troles=" + roles +
                ",\n\tusers=" + users +
                ",\n\tcake=" + cake +
                ",\n\tzakaz=" + zakaz +
                '}';
    }
}
