//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:10:58 AM MSK 
//


package by.it.naumenko.jd02_09.beens;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for cake complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cake">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_cake" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="name_cake" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size_cake" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight_cake" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bescuit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="decoration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cream" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price_cake" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cake", propOrder = {
    "idCake",
    "nameCake",
    "sizeCake",
    "weightCake",
    "bescuit",
    "decoration",
    "cream",
    "priceCake"
})
public class Cake {

    @XmlElement(name = "id_cake", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger idCake;
    @XmlElement(name = "name_cake", required = true)
    protected String nameCake;
    @XmlElement(name = "size_cake", required = true)
    protected String sizeCake;
    @XmlElement(name = "weight_cake", required = true)
    protected String weightCake;
    @XmlElement(required = true)
    protected String bescuit;
    @XmlElement(required = true)
    protected String decoration;
    @XmlElement(required = true)
    protected String cream;
    @XmlElement(name = "price_cake")
    protected float priceCake;

    /**
     * Gets the value of the idCake property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdCake() {
        return idCake;
    }

    /**
     * Sets the value of the idCake property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdCake(BigInteger value) {
        this.idCake = value;
    }

    /**
     * Gets the value of the nameCake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCake() {
        return nameCake;
    }

    /**
     * Sets the value of the nameCake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCake(String value) {
        this.nameCake = value;
    }

    /**
     * Gets the value of the sizeCake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeCake() {
        return sizeCake;
    }

    /**
     * Sets the value of the sizeCake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeCake(String value) {
        this.sizeCake = value;
    }

    /**
     * Gets the value of the weightCake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightCake() {
        return weightCake;
    }

    /**
     * Sets the value of the weightCake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightCake(String value) {
        this.weightCake = value;
    }

    /**
     * Gets the value of the bescuit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBescuit() {
        return bescuit;
    }

    /**
     * Sets the value of the bescuit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBescuit(String value) {
        this.bescuit = value;
    }

    /**
     * Gets the value of the decoration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecoration() {
        return decoration;
    }

    /**
     * Sets the value of the decoration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecoration(String value) {
        this.decoration = value;
    }

    /**
     * Gets the value of the cream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCream() {
        return cream;
    }

    /**
     * Sets the value of the cream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCream(String value) {
        this.cream = value;
    }

    /**
     * Gets the value of the priceCake property.
     * 
     */
    public float getPriceCake() {
        return priceCake;
    }

    /**
     * Sets the value of the priceCake property.
     * 
     */
    public void setPriceCake(float value) {
        this.priceCake = value;
    }

    @Override
    public String toString() {
        return "\n\t\tCake{" +
                "\n\t\t\tidCake=" + idCake +
                ",\n\t\t\tnameCake='" + nameCake + '\'' +
                ",\n\t\t\tsizeCake='" + sizeCake + '\'' +
                ",\n\t\t\tweightCake='" + weightCake + '\'' +
                ",\n\t\t\tbescuit='" + bescuit + '\'' +
                ",\n\t\t\tdecoration='" + decoration + '\'' +
                ",\n\t\t\tcream='" + cream + '\'' +
                ",\n\t\t\tpriceCake=" + priceCake +
                "\n\t\t}";
    }
}
