//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:10:58 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beens.jd02_09.naumenko.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.naumenko.jd02_09.beens;
