//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:10:58 AM MSK 
//


package by.it.naumenko.jd02_09.beens;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for roles complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="roles">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_roles" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "roles", propOrder = {
    "idRoles",
    "role"
})
public class Roles {

    @XmlElement(name = "id_roles", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger idRoles;
    @XmlElement(required = true)
    protected String role;

    /**
     * Gets the value of the idRoles property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdRoles() {
        return idRoles;
    }

    /**
     * Sets the value of the idRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdRoles(BigInteger value) {
        this.idRoles = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    @Override
    public String toString() {
        return "\n\t\tRoles{" +
                "\n\t\t\tidRoles=" + idRoles +
                ",\n\t\t\trole='" + role + '\'' +
                '}';
    }
}
