//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 01:10:58 AM MSK 
//


package by.it.naumenko.jd02_09.beens;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for zakaz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zakaz">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_zakaz" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="date_zakaz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="koltort" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="price_zakaz" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="id_user" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="id_cake" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zakaz", propOrder = {
    "idZakaz",
    "dateZakaz",
    "koltort",
    "priceZakaz",
    "idUser",
    "idCake"
})
public class Zakaz {

    @XmlElement(name = "id_zakaz", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger idZakaz;
    @XmlElement(name = "date_zakaz", required = true)
    protected String dateZakaz;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger koltort;
    @XmlElement(name = "price_zakaz")
    protected float priceZakaz;
    @XmlElement(name = "id_user", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger idUser;
    @XmlElement(name = "id_cake", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger idCake;

    /**
     * Gets the value of the idZakaz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdZakaz() {
        return idZakaz;
    }

    /**
     * Sets the value of the idZakaz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdZakaz(BigInteger value) {
        this.idZakaz = value;
    }

    /**
     * Gets the value of the dateZakaz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateZakaz() {
        return dateZakaz;
    }

    /**
     * Sets the value of the dateZakaz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateZakaz(String value) {
        this.dateZakaz = value;
    }

    /**
     * Gets the value of the koltort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKoltort() {
        return koltort;
    }

    /**
     * Sets the value of the koltort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKoltort(BigInteger value) {
        this.koltort = value;
    }

    /**
     * Gets the value of the priceZakaz property.
     * 
     */
    public float getPriceZakaz() {
        return priceZakaz;
    }

    /**
     * Sets the value of the priceZakaz property.
     * 
     */
    public void setPriceZakaz(float value) {
        this.priceZakaz = value;
    }

    /**
     * Gets the value of the idUser property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdUser() {
        return idUser;
    }

    /**
     * Sets the value of the idUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdUser(BigInteger value) {
        this.idUser = value;
    }

    /**
     * Gets the value of the idCake property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdCake() {
        return idCake;
    }

    /**
     * Sets the value of the idCake property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdCake(BigInteger value) {
        this.idCake = value;
    }

    @Override
    public String toString() {
        return "\n\t\tZakaz{" +
                "\n\t\t\tidZakaz=" + idZakaz +
                ",\n\t\t\tdateZakaz='" + dateZakaz + '\'' +
                ",\n\t\t\tkoltort=" + koltort +
                ",\n\t\t\tpriceZakaz=" + priceZakaz +
                ",\n\t\t\tidUser=" + idUser +
                ",\n\t\t\tidCake=" + idCake +
                "\n\t\t}";
    }
}
